project:
  name: khmer_ocr
  save_dir: outputs/khmer_ocr_100k_resnet_skel

dataset:
  charset: /home/thareah/Desktop/KHM_OCR/ocr_dataset_split_100k/charset.json
  path: /home/thareah/Desktop/KHM_OCR/ocr_dataset_split_100k/
  train:
    images: train
    labels: train/labels.txt
  val:
    images: val
    labels: val/labels.txt

preprocessing:
  image_height: 64
  image_width: 512
  grayscale: true
  normalize: true

model:
  architecture: resnet_bilstm_ctc_skel
  hidden_size: 256
  num_layers: 2
  dropout: 0.3

training:
  epochs: 30
  batch_size: 64
  learning_rate: 0.001
  optimizer: adam
  device: cuda
  num_workers: 4
  scheduler_patience: 5
  scheduler_factor: 0.5

checkpoint:
  save_every: 5
  save_best_model: true
  monitor: val_cer
  mode: min
  checkpoint_dir: outputs/khmer_ocr_100k_resnet_skel/checkpoints
  resume_from: null
